stdplus: srcrev bump 8a6eca3ae3..69a00d76b8
Patrick Williams (1):
      exception: remove source_location indirect

William A. Kennington III (23):
      str/cexpr: Delete clang exemption
      net/ether: Fixup constructors
      net/addr/ip: Fixup hash function signatures
      str/buf: Add allocation reducing string buffer
      str/conv: Add basic functions
      numeric/str: Add constexpr int encode
      numeric/str: Improve base10 encode performance
      numeric/str: Add constexpr int decode
      net/addr/ether: Add FromStr conversion
      net/addr/ether: Add ToStr conversion
      net/addr/ip: Add In4Addr FromStr conversion
      net/addr/ip: Add In4Addr ToStr conversion
      net/addr/ip: Add IPv6 FromStr conversion
      net/addr/ip: Add IPv6 ToStr conversion
      net/addr/ip: Add InAnyAddr FromStr conversion
      net/addr/ip: Add InAnyAddr ToStr conversion
      net/addr/subnet: Add ToStr conversion
      net/addr/subnet: Add FromStr conversion
      net/addr/ether: Add missing equal operator
      net/addr/ether: Add basic queries
      net/addr/subnet: Add netmask functions
      net/addr/subnet: Add hashing functions
      str/buf: Fix when sizeof(CharT) == sizeof(CharT*)

Change-Id: Ie518d47a5845beb32b79ee40650fd14749b084db
Signed-off-by: Andrew Geissler <openbmcbump-github@yahoo.com>