phosphor-logging:aspeed-pfr-tool: fix build failed at do_create_spdx task if build all targets at the same build directory
How to repdoruce it:
1. . setup ast2600-emmc build-ast2600
2. bitbake obmc-phosphor-image
3. Successfully build obmc-phosphor-image and created sstate-cache and SPDX
for ast2600-emmc target machine
4. Edit local.conf and set machine "ast2600-default"
5. bitbake obmc-phosphor-image

Got build errors:
ERROR: phosphor-logging-1.0+git-r1 do_create_spdx: Cannot find any SPDX file for recipe base-files, False sstate:base-files:ast2700_emmc-openbmc-linux:3.0.14:r0:ast2700_emmc:11: sstate:base-files::3.0.14:r0::11:
ERROR: Logfile of failure stored in: /home/jamin_lin/openbmc-ast2700/0111/build-ast2700/tmp/work/cortexa35-openbmc-linux/phosphor-logging/1.0+git/temp/log.do_create_spdx.2905089
ERROR: Task (/home/jamin_lin/openbmc-ast2700/0111/openbmc/meta-phosphor/recipes-phosphor/logging/phosphor-logging_git.bb:do_create_spdx) failed with exit code '1

Root Cause:
It searched the wrong base-files and it caused this build error.
"sstate:base-files:ast2700_emmc-openbmc-linux:3.0.14:r0:ast2700_emmc.

Solution:
It seems a SPDX metadata bug. According to the design of SPDX, https://github.com/openembedded/openembedded-core/blob/master/meta/classes/create-spdx-2.2.bbclass#L488
, it used the "BB_TASKDEPDATA" to get the dependent data.
However, sometimes it get the wrong dependent data due to do_collect_spdx_deps cache status.

Add do_collect_spdx_deps[nostamp] = "1" to tells BitBake to not generate a stamp file for a task, which implies the task should always be executed.
https://docs.yoctoproject.org/bitbake/2.6/bitbake-user-manual/bitbake-user-manual-metadata.html#variable-flags
It it a workaround solution.

Signed-off-by: Jamin Lin <jamin_lin@aspeedtech.com>
Change-Id: I900ba0eb9f8bec346ff1a946d5ae0fd8c2a4d860